services:
  - type: web
    name: sojourn-backend
    env: node
    buildCommand: |
      npm install --production=false
      npm install -g rimraf
      npm install --save-dev @types/jsonwebtoken @types/bcryptjs @types/cors @types/compression
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
    healthCheckPath: /api/health
    autoDeploy: true
